[package]
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"
name = "vision"
version = "0.3.3-a"

[dependencies]
stdweb = "0.4.20"
yew = "0.17.3"

[profile.release]
lto = true
opt-level = 's'
