[package]
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"
name = "vision"
version = "0.3.3"

[dependencies]
stdweb = "0.4.20"
yew = {version = "0.17.3", package = "yew-stdweb"}

[profile.release]
lto = true
opt-level = 's'
