[package]
name = "vision"
version = "0.2.2"
authors = ["Terkwood <metaterkhorn@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4"
yew = { git = "https://github.com/DenisKolodin/yew" }

[profile.release]
lto = true
opt-level = 's'
